#################################################################
#                                                               #
#                      Packages/Cameras                         #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:
    ## שינוי שמות ##
    camera.building_door:
      friendly_name: מצלמת דלת בניין

    camera.front_camera_dor:
      friendly_name: מצלמת דלת הבית

    camera.outside_camera_backwards:
      friendly_name: מצלמה חיצונית מרכזי
      
    camera.right_side_4mp:
      friendly_name: מצלמה צד ימין 4 מגה
      
    camera.left_side_2mp:
      friendly_name: מצלמה צד שמאל  2 מגה
      
    

    ## שינוי שמות לאוטומציה של כיבוי המצלמה ##
    automation.turn_on_xiaomi_cameras_if_nurit_and_avi_not_at_home:
      friendly_name: פעיל - אני ונורית לא בבית
      icon: mdi:cctv
      home_assistant: true
      
    automation.turn_off_xiaomi_cameras_if_avi_at_home:
      friendly_name: כיבוי מצלמה - אבי בבית
      icon: mdi:cctv
      home_assistant: true
      
    automation.turn_off_xiaomi_cameras_if_nurit_at_home:
      friendly_name: כיבוי מצלמה - נורית בבית
      icon: mdi:cctv
      home_assistant: true

    automation.turn_on_cctv_cameras_if_late_night:
      friendly_name: פעיל - מצלמה פעילה 23:00
      icon: mdi:cctv
      home_assistant: true

    automation.turn_off_xiaomi_cameras_if_morning_and_we_are_at_home:
      friendly_name: כיבוי מצלמה 7 בבוקר
      icon: mdi:cctv
      home_assistant: true

    automation.avi_wifi_off:
      friendly_name: הפעלת מצלמת שיאומי - וויפי אבי מכובה
      icon: mdi:wifi-off
      home-assistant: true

    automation.avi_wifi_on:
      friendly_name: כיבוי מצלמת שיאומי - וויפי אבי פעיל
      icon: mdi:wifi
      home-assistant: true  

    automation.nurit_wifi_off:
      friendly_name: הפעלת מצלמת שיאומי - וויפי נורית מכובה
      icon: mdi:wifi-off
      home-assistant: true  

    automation.nurit_wifi_on:
      friendly_name: כיבוי מצלמת שיאומי - וויפי נורית פעיל
      home-assistant: true

    automation.yakir_wifi_off:    
      friendly_name: זיהוי מצב ה וויפי של יקיר - לא זמין
      icon: mdi:wifi-off
      home-assistant: true

    automation.yakir_wifi_on:
      friendly_name: זיהוי מצב ה וויפי של יקיר - זמין
      icon: mdi:wifi
      home-assistant: true


#################################################################
#                                                               #
#                          cameras                            #
#                                                               #
#################################################################
camera:
  ## hikvision Camera ## 
    - platform: ffmpeg
      input: !secret input_01
      name:  building door

  ## hikvision Camera  dvr ## 
    - platform: ffmpeg
      input: !secret input_02
      name:  Outside Camera backwards
  
  ## foscam Camera ## 
    - platform: mjpeg
      mjpeg_url: !secret mjpeg_url
      name: front Camera Dor

  ## Dahua Camera 4mp ## 
    - platform: ffmpeg
      input: !secret camera4mp
      name: Right Side 4MP  
      
  ## hikvision Camera 2mp ## 
    - platform: ffmpeg
      input: !secret camera2mp
      name: Left Side 2MP

              
#################################################################
#                                                               #
#                           Groups                              #
#                                                               #
#################################################################
group:
  security cameras:
    name: camera
    view: no
    entities:
      - camera.building_door
      - camera.outside_camera_backwards
      
  high quality:
    name: Quality Camera
    view: no
    entities:
      - camera.right_side_4mp
      - camera.left_side_2mp

  inside the home:
    name: Home Fornt Dor Camera 
    view: no
    entities:
      - camera.front_camera_dor    
      

#################################################################
#                                                               #
#                           sensor                              # 
#                                                               #
#################################################################
# sensor:

#################################################################
#                                                               #
#                           scripts                             # 
#                                                               #
#################################################################
# script:



    
#################################################################
#                                                               #
#                         Automations                           #
#                                                               #
#################################################################
automation:
  - alias: frontdoor_snapshot
    trigger:
      platform: state
      entity_id: 'binary_sensor.door_window_sensor_158d0001ef3425'
      to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: 'device_tracker.avi_note8'
          state: 'not_home'
        - condition: state
          entity_id: 'device_tracker.iphone_nurit'
          state: 'not_home'
    action:
      - service: camera.snapshot
        data:
          entity_id: camera.front_camera_dor
          filename: "/config/tmp/front_house_{{ now().year }}_{{ now().month }}_{{ now().day }}_{{ now().hour }}_{{ now().minute }}.jpg"
      # - delay: 
      #   seconds: 5
      - service: notify.AviTelegram
        data:
          message: "הדלת נפתחה"
          data:
            photo:
              - file: "/config/tmp/front_house_{{ now().year }}_{{ now().month }}_{{ now().day }}_{{ now().hour }}_{{ now().minute }}.jpg"
                capture: Front House Camera              