#################################################################
#                                                               #
#                      Packages/weather                         #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:

#################################################################
#                                                               #
#                           Group                               #
#                                                               #
#################################################################
group:
  weather temp:
    name: weather
    view: no
    entities:
      - sensor.imsweather
      - sensor.outside_temp
      
      
#################################################################
#                                                               #
#                          Sensors                              #
#                                                               #
################################################################# 
sensor:

  - platform: command_line
    name: IMSWeather
    command: " curl get http://www.ims.gov.il/ims/rss/beer_sheva.xml 2>&1 | grep -ni .*title=  | grep -o [א-ת]* " 


#################################################################
#                                                               #
#                         Automations                           #
#                                                               #
#################################################################    
# automations: