#################################################################
#                                                               #
#              Packages/Greetet Card - ברוך הבא                 #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

# homeassistant:
#   customize:

      
#################################################################
#                                                               #
#                           Groups                              #
#                                                               #
#################################################################
# group: 


#################################################################
#                                                               #
#                           sensor                              # 
#                                                               #
#################################################################
sensor:
  - platform: template
    sensors:
      time_of_day:
        value_template: >
          {% set current_hour = strptime(states('sensor.time'), "%H:%M").hour %}
          {% if current_hour < 12 %}
            בוקר טוב, אבי
          {% elif 12 <= current_hour < 18 %}
            צהריים טובים, אבי
          {% elif 18 <= current_hour < 23 %}
            ערב טוב, אבי
          {% else %}
            לילה טוב, אבי
          {% endif %}

  - platform: template
    sensors:
      greeter_card_info:
        value_template: > 
          פרטי:
          האירוע הבא {{ as_timestamp(states.calendar.avi_abeksis.attributes.start_time) | timestamp_custom('- %d/%m/%Y בשעה %H:%M')  }}
  - platform: template
    sensors:
      greeter_card_info_2:
        value_template: > 
          עבודה:
          האירוע הבא {{ as_timestamp(states.calendar.work.attributes.start_time) | timestamp_custom('- %d/%m/%Y בשעה %H:%M')  }}
  - platform: template
    sensors:
      outside_temp:
        friendly_name: "Outside Temperature"
        # unit_of_measurement: '°C'
        value_template: "{{ states.weather.yweather.attributes.temperature }}"
        icon_template: >
          {% if is_state("weather.yweather", "sunny") -%}
             mdi:weather-sunny
          {% elif is_state('weather.yweather', 'clear-night') -%}
             mdi:weather-night
          {% elif is_state('weather.yweather', 'rain') -%}
             mdi:weather-rainy
          {% elif is_state('weather.yweather', 'snow') -%}
             mdi:weather-snowy
          {% elif is_state('weather.yweather', 'sleet') -%}
             mdi:weather-snowy-rainy
          {% elif is_state('weather.yweather', 'wind') -%}
             mdi:weather-windy-variant
          {% elif is_state('weather.yweather', 'fog') -%}
             mdi:weather-fog
          {% elif is_state('weather.yweather', 'cloudy') -%}
             mdi:weather-cloudy
          {% elif is_state('weather.yweather', 'partly-cloudy-day') -%}
             mdi:weather-partlycloudy
          {% elif is_state('weather.yweather', 'hail') -%}
             mdi:weather-hail
          {% elif is_state('weather.yweather', 'thunderstorm') -%}
             mdi:weather-lightning
          {% else %}
             mdi:help-circle
          {% endif %}

        entity_picture_template: >
          {% if is_state("weather.yweather", "sunny") -%}
             /local/weather_icons/animated/day.svg
          {% elif is_state('weather.yweather', 'clear-night') -%}
             /local/weather_icons/animated/night.svg
          {% elif is_state('weather.yweather', 'rain') -%}
             /local/weather_icons/animated/rain.svg
          {% elif is_state('weather.yweather', 'snow') -%}
             /local/weather_icons/animated/snow.svg
          {% elif is_state('weather.yweather', 'sleet') -%}
             /local/weather_icons/animated/sleet.svg
          {% elif is_state('weather.yweather', 'wind') -%}
             /local/weather_icons/animated/wind.svg
          {% elif is_state('weather.yweather', 'fog') -%}
             /local/weather_icons/animated/fog.svg
          {% elif is_state('weather.yweather', 'cloudy') -%}
             /local/weather_icons/animated/cloudy.svg
          {% elif is_state('weather.yweather', 'partly-cloudy-day') -%}
             /local/weather_icons/animated/partly-cloudy-day-1.svg
          {% elif is_state('weather.yweather', 'hail') -%}
             /local/weather_icons/animated/hail.svg
          {% elif is_state('weather.yweather', 'thunderstorm') -%}
             /local/weather_icons/animated/thunderstorm.svg
          {% elif is_state('weather.yweather', 'hail') -%}
             /local/weather_icons/animated/rainy-7.svg
          {% elif is_state('weather.yweather', 'lightning') -%}
             /local/weather_icons/animated/thunder.svg
          {% elif is_state('weather.yweather', 'lightning-rainy') -%}
             /local/weather_icons/animated/thunder.svg
          {% elif is_state('weather.yweather', 'partlycloudy') -%}
             /local/weather_icons/animated/cloudy.svg
          {% elif is_state('weather.yweather', 'pouring') -%}
             /local/weather_icons/animated/rainy-6.svg
          {% elif is_state('weather.yweather', 'rainy') -%}
             /local/weather_icons/animated/rainy-6.svg
          {% elif is_state('weather.yweather', 'snowy') -%}
             /local/weather_icons/animated/snowy-6.svg
          {% elif is_state('weather.yweather', 'snowy-rainy') -%}
             /local/weather_icons/animated/rainy-6.svg
          {% elif is_state('weather.yweather', 'windy') -%}
             /local/weather_icons/animated/cloudy.svg
          {% else %}
             /local/weather_icons/animated/help.svg
          {% endif %}

#################################################################
#                                                               #
#                           scripts                             # 
#                                                               #
#################################################################
# script:



    
#################################################################
#                                                               #
#                         Automations                           #
#                                                               #
#################################################################
# automation: