#Telegram
  - name: AviTelegram
    platform: telegram
    chat_id: !secret telgram_chat_id

## Nurit_iPhone ##
  - platform: ios
    name: iOSApp
    target: !secret iOSAppnuritTarget

## Android ##    
  - name: android
    platform: fcm-android

## Zanzito ##
  - name: Avi_mobile
    platform: zanzito
    device-name: avi   