  - platform: template
    covers:
      wbed_blinds:
        friendly_name: "תריס חשמלי בסלון"
        open_cover:
          service: script.blinds_up
        close_cover:
          service: script.blinds_down
        stop_cover:
          service: script.blinds_stop