  ## Weather prediction ##
  - platform: yr


  ## מידע מערכת ##
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_use_percent
      - type: processor_use
      - type: since_last_boot
  
  ## גודל בסיס הנתונים ##   
  - platform: filesize
    file_paths:
      - /config/home-assistant_v2.db

  ## בדיקת זמן פעולה של ha ##
  - platform: uptime
    name: Time Online         

  ## מהירות מעבד ##
  - platform: command_line
    name: 'CPU temp'
    unit_of_measurement: "°C" #temperature in C "°C"
    scan_interval: 120 #2 min
    command: " sshpass -p xxx ssh -o StrictHostKeyChecking=no user@1.1.1.1 'sensors |grep CPU | grep -o '[0-9][0-9].[0-9]' | head -1;' "
 

  # מציג את הגרסה האחרונה באתר הרשמי
  - platform: command_line
    command: python3 -c "import requests; print(requests.get('https://pypi.python.org/pypi/homeassistant/json').json()['info']['version'])"
    name: Current HA Version
  
  ## הצגת מספר הגרסה האחרונה המותקנת על המערכת ##
  - platform: command_line
    name: Installed version
    command: "head -5 /config/.HA_VERSION"

  ## שעה ותאריך ##
  - platform: time_date
    display_options:
      - 'date_time'
      - 'time'
      - 'date' 

  ## בדיקת מהירות אינטרנט ## 
  - platform: speedtest
    server_id: 9034
    monitored_conditions:
      - ping
      - download
      - upload

  ## cloudflare ##
  #https://www.home-assistant.io/components/sensor.dnsip/    
  - platform: dnsip
    scan_interval: 300 #5 min


  # חיישן טמפ וחיישן לחות ## 
  - platform: mqtt
    name: "Second floor temperature"
    state_topic: "tele/stairs/SENSOR"
    value_template: "{{ value_json['AM2301'].Temperature }}"
    unit_of_measurement: "°C"

  - platform: mqtt
    name: "Humidity second floor"
    state_topic: "tele/stairs/SENSOR"
    value_template: "{{ value_json['AM2301'].Humidity }}"
    homebridge_sensor_type: "humidity"
    unit_of_measurement: "%"


  # התחברות אחרונה ##
  - platform: authenticated 
  
  # גוגל #
  - platform: time_date
    display_options:
      - 'time'
          
           
# tautulli Plex
  - platform: tautulli
    api_key: !secret tautulli
    host: 1.1.1.1
    port: 8181
    attributes:
      - magic_title

# אבטחה - איזה כתובת אי פי התחברה #
  - platform: template
    sensors:
      authentication_known_ip_info:
        value_template: >-
          {% if is_state('sensor.last_successful_rature.attributes.new_ip', 'true') %}
            כן
          {% else %}
            לא
          {% endif %} 
          
          
          
## טמפ דיסקים בשרת unraid ##
  - platform: command_line
    name: 'HDD_sdi_temp'
    unit_of_measurement: "°C" #temperature in C "°C"
    scan_interval: 120 #2 min
    command: "hddtemp -n /dev/sdi"

  - platform: command_line
    name: 'HDD_sdc_temp'
    unit_of_measurement: "°C" #temperature in C "°C"
    scan_interval: 120 #2 min
    command: "hddtemp -n /dev/sdc"    
    
  - platform: command_line
    name: 'HDD_sdg_temp'
    unit_of_measurement: "°C" #temperature in C "°C"
    scan_interval: 120 #2 min
    command: "hddtemp -n /dev/sdg"
    
  - platform: command_line
    name: 'HDD_sdf_temp'
    unit_of_measurement: "°C" #temperature in C "°C"
    scan_interval: 120 #2 min
    command: "hddtemp -n /dev/sdf"
    
  - platform: command_line
    name: 'HDD_sde_temp'
    unit_of_measurement: "°C" #temperature in C "°C"
    scan_interval: 120 #2 min
    command: "hddtemp -n /dev/sde"
    
  - platform: command_line
    name: 'HDD_sdd_temp'
    unit_of_measurement: "°C" #temperature in C "°C"
    scan_interval: 120 #2 min
    command: "hddtemp -n /dev/sdd" 

  - platform: command_line
    name: 'HDD_sdh_temp'
    unit_of_measurement: "°C" #temperature in C "°C"
    scan_interval: 120 #2 min
    command: "hddtemp -n /dev/sdh" 
    
  - platform: command_line
    name: 'HDD_sdb_temp'
    unit_of_measurement: "°C" #temperature in C "°C"
    scan_interval: 120 #2 min
    command: "hddtemp -n /dev/sdb"     


###### Latest config backup time
  - platform: command_line
    command: "bash /config/bin/latest_Hass_backup.py"
    name: 'Latest HA Backup'
    scan_interval: 43200 #12 Hours

  # Radarr #
  - platform: radarr_upcoming_media
    api_key: !secret radarr
    host: 1.1.1.1
    port: 7878
    days: 120
    ssl: false

  - platform: mqtt
    name: "BlitzWolf shp1 energy today"
    state_topic: "tele/bw-shp1/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Today"] }}'
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "BlitzWolf shp1 yesterday"
    state_topic: "tele/bw-shp1/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Yesterday"] }}'
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "BlitzWolf shp1 total"
    state_topic: "tele/bw-shp1/SENSOR"
    value_template: '{{ value_json["ENERGY"]["Total"] }}'
    unit_of_measurement: "kWh"
  - platform: mqtt
    name: "BlitzWolf shp1 total cost"
    state_topic: "tele/bw-shp1/SENSOR"
    value_template: '{{ (value_json["ENERGY"]["Total"] * 0.5404) | round(3) }}'
    #ILS OR USD (Depends on local currency) Just change the value of "0.5404" to your local elctricity price
    unit_of_measurement: "₪" # USD / Other local currency           